-- URL_MENUS definition

-- Drop table

-- DROP TABLE URL_MENUS;

CREATE TABLE URL_MENUS (
	URL_ID VARCHAR(3) NOT NULL,
	URL_TEXT BLOB SUB_TYPE TEXT,
	DESCRIPCION VARCHAR(100) NOT NULL,
	CONSTRAINT PK_URL_MENUS PRIMARY KEY (URL_ID),
	CONSTRAINT URL_MENUS_UNIQUE UNIQUE (DESCRIPCION)
);